# -*- coding: utf-8 -*-
"""Deterministic citation pipeline: cite markers -> styled text + reference slides.

The deck's single citation database is ``<deck>/references.bib`` (see
``references/bibtex-guide.md`` for how agents fill it). Slides carry only
cite MARKERS; this script renders them and generates the bibliography:

1. ``[@key]`` / ``[@key, p. 12]`` in any active slide file is replaced by
   ``<!--cite:key|loc-->Rendered Short Form<!--/cite-->`` via citeproc-py
   (style = any CSL in references/csl or ~/.slidecraft/csl). Idempotent:
   re-running (e.g. after switching --style) regenerates the text between
   the markers from the key, so rendered text is never hand-edited.
2. ``slides/references.md`` (+ ``references-2.md`` ...) are (re)generated
   from the CITED non-image entries, paginated (--per-page). Bib entries
   tagged ``keywords = {image}`` go to ``slides/image-sources*.md`` instead
   (ALL image entries, cited or not), photos and AI assets grouped.
3. The ``slides.md`` manifest is kept in sync: the consecutive run of
   references*/image-sources* imports is replaced by the new page list
   (inserted before the thank-you slide when absent). Orphaned generated
   pages are deleted (only files carrying the AUTO-GENERATED marker).
4. Cross-checks (the "credits linter"): unknown cite keys -> ERROR;
   bib entries never cited -> warn; ``/figures/...`` files used on slides
   with neither a course-book filename pattern nor an image entry naming
   them -> warn; image entries whose noted file is unused -> warn.

Usage:
    python -m slidecraft.scripts.render_references --deck <deck-dir>
        [--style apa-7th] [--per-page 7] [--img-per-page 8]
        [--bookfig-pattern "ch\\d+_fig_"] [--check] [--no-narrative]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:  # package-relative first, plain module fallback (matches sibling scripts)
    from slidecraft.scripts.format_citations import (
        CitationSpec, format_inline, format_bibliography)
except ImportError:  # pragma: no cover
    from format_citations import (  # type: ignore
        CitationSpec, format_inline, format_bibliography)

AUTOGEN_MARK = "<!-- AUTO-GENERATED by render_references; do not edit by hand -->"
RAW_CITE_RE = re.compile(r"\[@([A-Za-z0-9_:.\-]+)(?:,\s*([^\]]+?))?\]")
RENDERED_CITE_RE = re.compile(r"<!--cite:([^|>]+)\|([^>]*)-->(.*?)<!--/cite-->", re.DOTALL)
IMG_RE = re.compile(r'<img src="/figures/([^"]+)"')


# --------------------------------------------------------------------------
# Minimal bib field scanner (keywords/note routing only; rendering is
# citeproc-py's job). Handles the guide-enforced format: ``field = {...}``
# with at most one level of nested braces, entries opened by ``@type{key,``.
# --------------------------------------------------------------------------

def scan_bib_fields(bib_path: Path) -> dict[str, dict[str, str]]:
    text = bib_path.read_text(encoding="utf-8")
    entries: dict[str, dict[str, str]] = {}
    for m in re.finditer(r"@(\w+)\s*\{\s*([^,\s]+)\s*,", text):
        etype, key = m.group(1).lower(), m.group(2)
        if etype in ("comment", "preamble", "string"):
            continue
        # capture the entry body up to the matching closing brace
        depth, i = 1, m.end()
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        body = text[m.end():i - 1]
        fields = {"_type": etype}
        for fm in re.finditer(r"(\w+)\s*=\s*\{((?:[^{}]|\{[^{}]*\})*)\}", body):
            fields[fm.group(1).lower()] = re.sub(r"\s+", " ", fm.group(2)).strip()
        entries[key] = fields
    return entries


def is_image_entry(fields: dict[str, str]) -> bool:
    return "image" in [k.strip() for k in fields.get("keywords", "").split(",")]


# --------------------------------------------------------------------------
# Slide scanning / rewriting
# --------------------------------------------------------------------------

def manifest_slugs(deck: Path) -> list[str]:
    mani = (deck / "slides.md").read_text(encoding="utf-8")
    return re.findall(r"src: \./slides/([^\s]+)\.md", mani)


def _comment_spans(text: str) -> list[tuple[int, int]]:
    """Spans of top-level ``<!-- ... -->`` comments (e.g. presenter notes)."""
    return [m.span() for m in re.finditer(r"<!--.*?-->", text, re.DOTALL)]


def render_markers(text: str, bib: Path, style: str, narrative: bool,
                   cited: list[str], unknown: set[str], cache: dict) -> str:
    """Replace raw + previously rendered markers; record cited keys in order.

    Outside HTML comments the replacement is wrapped in
    ``<!--cite:key|loc-->...<!--/cite-->`` so it can be re-rendered (style
    switches). INSIDE comments (presenter notes) the raw ``[@key]`` marker
    is KEPT verbatim: nesting comments would break the notes block, and
    replacing without a marker would drop the key from the reference list
    on the next run. The presenter sees the compact LaTeX-like marker; the
    key still counts as cited.
    """

    def render(key: str, loc: str) -> str | None:
        ck = (key, loc)
        if ck not in cache:
            try:
                cache[ck] = format_inline(
                    bib, [CitationSpec(key, loc or None)], style=style,
                    narrative=narrative)
            except KeyError:
                cache[ck] = None
        return cache[ck]

    def make_sub(wrap: bool):
        def sub(m: re.Match) -> str:
            key, loc = m.group(1).strip(), (m.group(2) or "").strip()
            out = render(key, loc)
            if out is None:
                unknown.add(key)
                return m.group(0)
            if key not in cited:
                cited.append(key)
            return (f"<!--cite:{key}|{loc}-->{out}<!--/cite-->"
                    if wrap else out)
        return sub

    # Pass 1: re-render previously wrapped markers (these are never inside
    # other comments by construction).
    text = RENDERED_CITE_RE.sub(make_sub(wrap=True), text)

    # Pass 2: raw [@key] markers — replaced+wrapped outside comments; kept
    # verbatim (but validated and counted as cited) inside comments.
    spans = _comment_spans(text)

    def sub_raw(m: re.Match) -> str:
        inside = any(a <= m.start() < b for a, b in spans)
        if inside:
            key, loc = m.group(1).strip(), (m.group(2) or "").strip()
            if render(key, loc) is None:
                unknown.add(key)
            elif key not in cited:
                cited.append(key)
            return m.group(0)
        return make_sub(wrap=True)(m)

    text = RAW_CITE_RE.sub(sub_raw, text)
    return text


# --------------------------------------------------------------------------
# Generated pages
# --------------------------------------------------------------------------

def find_footer_date(deck: Path, slugs: list[str]) -> tuple[str, str]:
    for slug in slugs:
        p = deck / "slides" / f"{slug}.md"
        if not p.is_file():
            continue
        t = p.read_text(encoding="utf-8")
        if AUTOGEN_MARK in t:
            continue
        fm = re.search(r"::footer::\n(.+)\n", t)
        dm = re.search(r"::date::\n(.+)\n", t)
        if fm and dm:
            return fm.group(1).strip(), dm.group(1).strip()
    return "", ""


def page_md(title: str, body_html: str, footer: str, date: str) -> str:
    return (f"---\nlayout: slide4\n---\n{AUTOGEN_MARK}\n\n"
            f"::title::\n{title}\n\n::ph-1::\n<div class=\"srcref\">\n"
            f"{body_html}\n</div>\n\n::footer::\n{footer}\n\n::date::\n{date}\n")


def chunk(lst: list, n: int) -> list[list]:
    return [lst[i:i + n] for i in range(0, len(lst), n)] or [[]]


def image_entry_html(fields: dict[str, str]) -> str:
    author = fields.get("author", "n.a.").strip("{}")
    title = fields.get("title", "Untitled")
    year = fields.get("year", "n.d.")
    org = fields.get("organization") or fields.get("howpublished") or ""
    url = fields.get("url", "")
    note = fields.get("note", "")
    kind = ("AI-generated image" if "ai-generated" in fields.get("keywords", "")
            else "Photograph")
    parts = [f"{author}. ({year}). <em>{title}</em> [{kind}]."]
    if org:
        parts.append(f"{org}.")
    if url:
        parts.append(f"{url}")
    if note:
        parts.append(f"({note})")
    return '<p class="se">' + " ".join(parts) + "</p>"


# --------------------------------------------------------------------------
# Manifest sync
# --------------------------------------------------------------------------

def sync_manifest(deck: Path, base: str, new_slugs: list[str]) -> None:
    """Replace the consecutive run of ``base*`` imports with ``new_slugs``."""
    mani_p = deck / "slides.md"
    text = mani_p.read_text(encoding="utf-8")
    run_re = re.compile(
        rf"(?:---\nsrc: \./slides/{re.escape(base)}(?:-\d+)?\.md\n---\n\n?)+")
    block = "".join(f"---\nsrc: ./slides/{s}.md\n---\n\n" for s in new_slugs)
    if run_re.search(text):
        text = run_re.sub(block, text, count=1)
    elif new_slugs:
        anchor = "---\nsrc: ./slides/thank-you.md\n---\n"
        text = (text.replace(anchor, block + anchor, 1)
                if anchor in text else text + "\n" + block)
    mani_p.write_text(text, encoding="utf-8", newline="\n")


def cleanup_orphans(deck: Path, base: str, keep: list[str]) -> list[str]:
    removed = []
    for p in sorted((deck / "slides").glob(f"{base}*.md")):
        if p.stem in keep:
            continue
        if re.fullmatch(rf"{re.escape(base)}(-\d+)?", p.stem) and \
                AUTOGEN_MARK in p.read_text(encoding="utf-8"):
            p.unlink()
            removed.append(p.stem)
    return removed


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--deck", required=True, type=Path)
    ap.add_argument("--style", default="apa-7th")
    ap.add_argument("--per-page", type=int, default=7)
    ap.add_argument("--img-per-page", type=int, default=8)
    ap.add_argument("--bookfig-pattern", default=r"ch\d+_fig_")
    ap.add_argument("--no-narrative", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="report only; write nothing")
    a = ap.parse_args(argv)
    deck: Path = a.deck
    bib = deck / "references.bib"
    if not bib.is_file():
        print(f"ERROR: {bib} not found. Create it per references/bibtex-guide.md")
        return 1

    fields_by_key = scan_bib_fields(bib)
    slugs = manifest_slugs(deck)
    footer, date = find_footer_date(deck, slugs)

    cited: list[str] = []
    unknown: set[str] = set()
    used_figs: set[str] = set()
    cache: dict = {}
    changed = []
    for slug in slugs:
        p = deck / "slides" / f"{slug}.md"
        if not p.is_file():
            continue
        text = p.read_text(encoding="utf-8")
        if AUTOGEN_MARK in text:
            continue
        used_figs.update(IMG_RE.findall(text))
        new = render_markers(text, bib, a.style, not a.no_narrative,
                             cited, unknown, cache)
        if new != text:
            changed.append(slug)
            if not a.check:
                p.write_text(new, encoding="utf-8", newline="\n")

    # ---- references pages (cited, non-image, in citation order) ----
    ref_keys = [k for k in cited if not is_image_entry(fields_by_key.get(k, {}))]
    pages = chunk(ref_keys, a.per_page) if ref_keys else []
    ref_slugs = []
    for i, keys in enumerate(pages):
        entries = format_bibliography(bib, keys, style=a.style)
        body = "\n".join(f'<p class="se">{e}</p>' for e in entries)
        slug = "references" if i == 0 else f"references-{i + 1}"
        title = "References" if i == 0 else "References (cont.)"
        ref_slugs.append(slug)
        if not a.check:
            (deck / "slides" / f"{slug}.md").write_text(
                page_md(title, body, footer, date), encoding="utf-8", newline="\n")

    # ---- image-sources pages (ALL image entries; photos then AI) ----
    img_items = [(k, f) for k, f in fields_by_key.items() if is_image_entry(f)]
    photos = [(k, f) for k, f in img_items if "ai-generated" not in f.get("keywords", "")]
    ai = [(k, f) for k, f in img_items if "ai-generated" in f.get("keywords", "")]
    blocks: list[str] = []
    if photos:
        blocks.append('<p class="sh"><strong>Photographs</strong></p>')
        blocks += [image_entry_html(f) for _, f in photos]
    if ai:
        blocks.append('<p class="sh"><strong>AI-generated figures</strong></p>')
        blocks += [image_entry_html(f) for _, f in ai]
    img_pages = chunk(blocks, a.img_per_page) if blocks else []
    img_slugs = []
    for i, lines in enumerate(img_pages):
        slug = "image-sources" if i == 0 else f"image-sources-{i + 1}"
        title = "Image sources" if i == 0 else "Image sources (cont.)"
        img_slugs.append(slug)
        if not a.check:
            (deck / "slides" / f"{slug}.md").write_text(
                page_md(title, "\n".join(lines), footer, date),
                encoding="utf-8", newline="\n")

    if not a.check:
        sync_manifest(deck, "references", ref_slugs)
        sync_manifest(deck, "image-sources", img_slugs)
        removed = (cleanup_orphans(deck, "references", ref_slugs)
                   + cleanup_orphans(deck, "image-sources", img_slugs))
    else:
        removed = []

    # ---- cross-checks -------------------------------------------------
    status = 0
    if unknown:
        print("ERROR unknown cite keys (add to references.bib):",
              ", ".join(sorted(unknown)))
        status = 1
    uncited = [k for k, f in fields_by_key.items()
               if k not in cited and not is_image_entry(f)]
    if uncited:
        print("warn: bib entries never cited:", ", ".join(sorted(uncited)))
    bookfig = re.compile(a.bookfig_pattern)
    noted_files = " ".join(f.get("note", "") for _, f in img_items)
    for fig in sorted(used_figs):
        base = fig.rsplit("/", 1)[-1]
        if bookfig.search(base):
            continue
        if base not in noted_files:
            print(f"warn: /figures/{fig} has no image entry naming it "
                  f"(add note = {{... {base}}})")
    for k, f in img_items:
        m = re.search(r"([\w.\-]+\.(?:png|jpe?g|svg|gif))", f.get("note", ""))
        if m and not any(m.group(1) in u for u in used_figs):
            print(f"warn: image entry '{k}' notes file {m.group(1)}, "
                  f"which no active slide uses")

    print(f"cited: {len(cited)} keys | references pages: {len(ref_slugs)} | "
          f"image pages: {len(img_slugs)} | slides rewritten: {len(changed)}"
          f"{' (check mode, nothing written)' if a.check else ''}"
          + (f" | removed orphans: {removed}" if removed else ""))
    return status


if __name__ == "__main__":
    sys.exit(main())
